### ISSUE TITLE
[Bug]报了个TypeError

### ISSUE THREAD

**Issue by sjt-2024** [hite4044/ClassOneComputerKiller#1]
# 报错前操作
第一第二步照做,第三步我是在本机测试,所以没改,运行main.py时报错  
# 错误情况
![image](https://github.com/user-attachments/assets/327187b4-4001-4a07-80e4-d3825248a6c7)
# 运行环境
Windows 10(版本2004,OS内部版本19041.264)
# 建议
个人感觉这是个意料之外的bug,所以项目发布前可以做下多环境内测.
代码太长看得头大,建议写下注释,模块文档,类文档和函数文档,写下更好.

**Comment by hite4044** [comment]
尝试提取某个系统图标时，该图标不存在，应该是因为你的系统不包含此图标，我稍后将会把图标包含在项目文件里
你的建议已收到，我会尝试改进的

**Comment by Minemetero** [comment]
确实，多写些文档吧
